language: java
sudo: false
install: mvn -Pstaging install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -Pstaging test -B
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    - cdi-dev@lists.jboss.org
  irc:
    channels:
      - "chat.freenode.net#cdi-dev"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
